# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-codely-tf-states"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-east-1"
  }
}
